/* Service Worker — Meu Dicionário PT-BR
 *
 * Strategy summary (see README for the full offline contract):
 *  - App shell (html/css/js/svg)  -> stale-while-revalidate, precached on install
 *  - Navigations                  -> network-first, cached index.html as offline fallback
 *  - Bundled resource packs       -> cache-first (versioned, immutable)
 *  - Cross-origin APIs (AI / TTS) -> never cached by the SW (the app caches audio in IndexedDB)
 *  - User data                     -> lives in IndexedDB, never touches the SW
 */

const VERSION = '1.0.0';
const STATIC_CACHE = `plp-static-v${VERSION}`;
const PACK_CACHE = `plp-packs-v${VERSION}`;
const OFFLINE_PAGE = './offline.html';

const PRECACHE_URLS = [
  './',
  './index.html',
  './offline.html',
  './manifest.webmanifest',
  './app-config.js',
  './src/styles/app.css',
  './src/styles/pages.css',
  './src/main.js',
  './assets/icons/favicon.svg',
  './assets/icons/icon-192.png',
  './assets/icons/apple-touch-icon.png'
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(STATIC_CACHE);
    await cache.addAll(PRECACHE_URLS.map((u) => new Request(u, { cache: 'reload' }))).catch(() => {});
    // `build-manifest.json` is generated by scripts/build.mjs and lists every
    // emitted file, so a production build precaches the whole app.
    try {
      const res = await fetch('./build-manifest.json', { cache: 'reload' });
      if (res.ok) {
        const files = await res.json();
        if (Array.isArray(files)) {
          // Individual adds: one missing file must not abort the whole precache.
          await Promise.allSettled(files.map((file) => cache.add(new Request(file, { cache: 'reload' }))));
        }
      }
    } catch { /* dev mode: runtime caching will pick files up */ }
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map((key) => {
      if (key === STATIC_CACHE || key === PACK_CACHE) return null;
      if (!key.startsWith('plp-')) return null;
      return caches.delete(key);
    }));
    if (self.registration.navigationPreload) {
      try { await self.registration.navigationPreload.disable(); } catch { /* noop */ }
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'SKIP_WAITING') { self.skipWaiting(); return; }
  if (data.type === 'GET_VERSION') {
    event.source?.postMessage({ type: 'VERSION', version: VERSION });
    return;
  }
  if (data.type === 'CACHE_URLS' && Array.isArray(data.urls)) {
    event.waitUntil((async () => {
      const cache = await caches.open(data.cache === 'packs' ? PACK_CACHE : STATIC_CACHE);
      await Promise.all(data.urls.map((u) => cache.add(new Request(u, { cache: 'reload' })).catch(() => null)));
      event.source?.postMessage({ type: 'CACHE_URLS_DONE', count: data.urls.length });
    })());
    return;
  }
  if (data.type === 'CLEAR_APP_CACHE') {
    event.waitUntil((async () => {
      await Promise.all([caches.delete(STATIC_CACHE), caches.delete(PACK_CACHE)]);
      event.source?.postMessage({ type: 'CLEAR_APP_CACHE_DONE' });
    })());
  }
});

function isSameOrigin(url) {
  return url.origin === self.location.origin;
}

function isPackRequest(url) {
  return isSameOrigin(url) && url.pathname.includes('/data/packs/');
}

function isStaticAsset(url) {
  if (!isSameOrigin(url)) return false;
  return /\.(?:js|mjs|css|json|webmanifest|svg|png|jpg|jpeg|webp|ico|woff2?|ttf|txt|md)$/i.test(url.pathname);
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);

  // Cross-origin (AI API, remote TTS, remote catalogs) is never intercepted:
  // the app is responsible for caching what must work offline.
  if (!isSameOrigin(url)) return;

  if (req.mode === 'navigate') {
    event.respondWith(networkFirstNavigation(req));
    return;
  }

  if (isPackRequest(url)) {
    event.respondWith(cacheFirst(req, PACK_CACHE));
    return;
  }

  if (isStaticAsset(url)) {
    event.respondWith(staleWhileRevalidate(req, STATIC_CACHE));
    return;
  }
});

async function networkFirstNavigation(req) {
  const cache = await caches.open(STATIC_CACHE);
  try {
    const fresh = await fetch(req);
    if (fresh && fresh.ok) {
      cache.put('./index.html', fresh.clone()).catch(() => {});
      return fresh;
    }
    throw new Error('bad response');
  } catch {
    const cached = (await cache.match('./index.html')) || (await cache.match('./'));
    if (cached) return cached;
    const offline = await cache.match(OFFLINE_PAGE);
    if (offline) return offline;
    return new Response(
      '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font:16px -apple-system,sans-serif;padding:24px">离线，且尚未缓存应用外壳。请联网打开一次后重试。</body>',
      { headers: { 'Content-Type': 'text/html; charset=utf-8' }, status: 200 }
    );
  }
}

async function cacheFirst(req, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(req, { ignoreSearch: false });
  if (cached) return cached;
  try {
    const fresh = await fetch(req);
    if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone()).catch(() => {});
    return fresh;
  } catch (err) {
    return new Response(JSON.stringify({ error: 'offline-and-not-cached', url: req.url }), {
      status: 504,
      headers: { 'Content-Type': 'application/json; charset=utf-8' }
    });
  }
}

async function staleWhileRevalidate(req, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(req);
  const network = fetch(req).then((res) => {
    if (res && res.ok && res.type === 'basic') cache.put(req, res.clone()).catch(() => {});
    return res;
  }).catch(() => null);
  if (cached) return cached;
  const fresh = await network;
  if (fresh) return fresh;
  return new Response('', { status: 504, statusText: 'Offline' });
}
