#!/usr/bin/env node
/**
 * Zero-dependency build.
 *
 *   npm run build
 *
 * Produces `dist/` containing exactly the files a static host needs, writes
 * `build-manifest.json` (used by the service worker to precache everything) and
 * bakes environment variables into `app-config.js`.
 *
 * Environment variables (all optional):
 *   PLP_AI_PROXY_URL      default /api/ai
 *   PLP_TTS_PROXY_URL     default /api/tts
 *   PLP_AI_TRANSPORT      auto | proxy | openai | mock | none
 *   PLP_TTS_TRANSPORT     auto | proxy | openai | device | none
 *   PLP_RESOURCE_CATALOG  remote catalog URL
 *   PLP_VERSION           version stamp
 *   PLP_ALLOW_MOCK_AI     true | false
 */

import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('../', import.meta.url)));
const DIST = join(ROOT, 'dist');

const INCLUDE = [
  'index.html',
  'offline.html',
  'manifest.webmanifest',
  'sw.js',
  'src',
  'assets',
  'api',
  'README.md',
  'QUICKSTART.md',
  'LICENSE-DATA.md',
  'vercel.json',
  'netlify.toml'
];

const VERSION = process.env.PLP_VERSION || (await readPackageVersion());

async function readPackageVersion() {
  try {
    const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'));
    return pkg.version || '1.0.0';
  } catch { return '1.0.0'; }
}

function buildAppConfig() {
  const cfg = {
    version: VERSION,
    aiProxyUrl: process.env.PLP_AI_PROXY_URL ?? '/api/ai',
    ttsProxyUrl: process.env.PLP_TTS_PROXY_URL ?? '/api/tts',
    aiTransport: process.env.PLP_AI_TRANSPORT ?? 'auto',
    ttsTransport: process.env.PLP_TTS_TRANSPORT ?? 'auto',
    resourceCatalogUrl: process.env.PLP_RESOURCE_CATALOG ?? '',
    allowMockAI: (process.env.PLP_ALLOW_MOCK_AI ?? 'true') !== 'false'
  };
  return `/**
 * Generated by scripts/build.mjs — do not edit dist/app-config.js by hand.
 * Edit the root app-config.js (or set PLP_* environment variables) instead.
 */
window.__APP_CONFIG__ = ${JSON.stringify(cfg, null, 2)};
`;
}

async function listFiles(dir, base = dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...await listFiles(full, base));
    else out.push(`./${relative(base, full).split(/[\\/]/).join('/')}`);
  }
  return out;
}

async function exists(path) {
  try { await stat(path); return true; } catch { return false; }
}

async function main() {
  console.log(`\n· build ${VERSION}`);
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  for (const item of INCLUDE) {
    const from = join(ROOT, item);
    if (!(await exists(from))) continue;
    await cp(from, join(DIST, item), { recursive: true });
  }

  await writeFile(join(DIST, 'app-config.js'), buildAppConfig(), 'utf8');

  // stamp the version into sw.js so cache names match the release
  const swPath = join(DIST, 'sw.js');
  const sw = await readFile(swPath, 'utf8');
  await writeFile(swPath, sw.replace(/const VERSION = '[^']+';/, `const VERSION = '${VERSION}';`), 'utf8');

  // build manifest -> complete precache for offline use
  // The precache list covers everything the browser needs offline. Serverless
  // endpoints and docs are intentionally excluded (they would 404 on hosts
  // without functions, and the SW would waste cache space on them).
  const EXCLUDE_FROM_PRECACHE = [
    /^\.\/build-manifest\.json$/,
    /^\.\/api\//,
    /^\.\/netlify\//,
    /^\.\/README\.md$/,
    /^\.\/QUICKSTART\.md$/,
    /^\.\/LICENSE-DATA\.md$/,
    /^\.\/vercel\.json$/,
    /^\.\/netlify\.toml$/
  ];
  const files = (await listFiles(DIST)).filter((f) => !EXCLUDE_FROM_PRECACHE.some((re) => re.test(f)));
  await writeFile(join(DIST, 'build-manifest.json'), JSON.stringify(files, null, 2), 'utf8');

  const bytes = (await Promise.all(files.map(async (f) => (await stat(join(DIST, f.replace(/^\.\//, '')))).size)))
    .reduce((a, b) => a + b, 0);

  console.log(`· ${files.length} files → dist/ (${(bytes / 1024).toFixed(0)} KB uncompressed)`);
  console.log('· deploy the dist/ folder to any static host (see README)\n');
}

main().catch((err) => {
  console.error('build failed:', err);
  process.exit(1);
});
